spring:
  datasource:
#    url: jdbc:mysql://mysql_db:3306/cloudfilestoragedb
#    url: jdbc:postgresql://postgresql_db:5432/cloudfilestoragedb
    url: jdbc:postgresql://localhost:5432/cloudfilestoragedb
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
