spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${HOST}:5432/${POSTGRES_DATABASE}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
  servlet:
    multipart:
      max-file-size: ${MAX_UPLOAD_FILE_SIZE}
      max-request-size: ${MAX_UPLOAD_FILE_SIZE}

flyway:
  url: jdbc:postgresql://${HOST}:5432
  username: ${POSTGRES_USERNAME}
  password: ${POSTGRES_PASSWORD}

minio:
  url: ${MINIO_URL}
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}
  bucketName: ${MINIO_BUCKET_NAME}

#max-upload-file-size: ${MAX_UPLOAD_FILE_SIZE}
